name: Deploy to AWS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: perfect-car-picker-backend
  TF_VERSION: 1.5.0

  HF_API_KEY: ${{ secrets.HF_API_KEY }}

  TF_VAR_project_name: "perfect-car-picker"
  TF_VAR_aws_region: "us-east-1"
  TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}

  # network tf vars
  TF_VAR_github_repo_url: ${{ vars.TF_VAR_GITHUB_REPO_URL }} 
  TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_VPC_CIDR }}
  TF_VAR_public_subnet_cidr: ${{ secrets.TF_VAR_PUBLIC_SUBNET_CIDR }}
  TF_VAR_private_subnet_1_cidr: ${{ secrets.TF_VAR_PRIVATE_SUBNET_1_CIDR }}
  TF_VAR_private_subnet_2_cidr: ${{ secrets.TF_VAR_PRIVATE_SUBNET_2_CIDR }}
  TF_VAR_app_port: ${{ secrets.TF_VAR_APP_PORT }}
  TF_VAR_ssh_port: ${{ secrets.TF_VAR_SSH_PORT }}
  TF_VAR_db_port: ${{ secrets.TF_VAR_DB_PORT }}

permissions:
  contents: read

jobs:
  deploy:
    name: Terraform & Docker Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: .
      run: terraform init

    # ecr
    - name: Terraform Apply (Target ECR)
      working-directory: .
      run: |
        terraform apply -target=aws_ecr_repository.lambda_repo -auto-approve

    # pre compile python libraries
    - name: Pre-compile Backend Dependencies
      run: |
        cd backend
        mkdir -p package
        pip install \
          --target ./package \
          -r requirements.txt \
          --platform manylinux2014_x86_64 \
          --only-binary=:all: \
          --implementation cp \
          --python-version 3.11 \
          --upgrade

    # backend push
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build --provenance=false -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::notice::Pushed image to $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    # tf apply
    - name: Terraform Apply (Full Infrastructure)
      working-directory: .
      run: terraform apply -auto-approve

    - name: Force Lambda Update
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        FUNCTION_NAME: "${{ env.TF_VAR_project_name }}-logic"
      run: |
        echo "ðŸ”„ Forcing Lambda to pull new image..."
        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          --publish
        echo "Lambda updated successfully."

    # output
    - name: Output URLs
      working-directory: .
      run: |
        terraform refresh

        echo "Deployment Complete!"
        echo "API Endpoint: $(terraform output -raw api_url)"
        echo "Website URL: $(terraform output -raw website_url)"